name: Lints

on:
  workflow_dispatch:

steps:
  - uses: actions/checkout@v3.5.0
  - uses: ricardochaves/python-lint@v1.4.0
    with:
      use-pycodestyle: false
      use-flake8: false
      use-black: false
      use-mypy: false
      use-isort: false
