name: Lints

on:
  schedule:
    # Run each Sun
    - cron: '0 0 * * 0'
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.0
      - run: |
          pip install -r requirements.txt
          pip install pylint bandit
          pylint src/swin
          bandit -r src/swin