name: Lints

on:
  schedule:
    # Run each Sun
    - cron: '0 0 * * 0'
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.0
  
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pylint static code analyser
        run: |
          pip install pylint
          pylint src/swin

      - name: Run Bandit security analyser
        run: |
          pip install bandit
          bandit -r src/swin